# Change these first
owner: killbillsdev # Your GitHub organization or username, where this repository lives
repo: StatusPage # The name of this repository


sites:
  - name: KillBills Website [ https://killbills.co ]
    url: https://killbills.co
    icon: https://cdn.prod.website-files.com/65266c5d2cc55475b719db3a/65266c5d2cc55475b719dbea_favicon-killbillz%201.svg
    assignees:
      - basileFernandez

  - name: KillBills Stores Map [ https://maps.killbills.co ]
    url: https://maps.killbills.co
    icon: https://cdn.prod.website-files.com/65266c5d2cc55475b719db3a/65266c5d2cc55475b719dbea_favicon-killbillz%201.svg
    assignees:
      - bgdtc
      - shurimaTN
      - basileFernandez

  - name: KillBills Partner's App [ https://partners.killbills.co ]
    url: https://partners.killbills.co
    icon: https://cdn.prod.website-files.com/65266c5d2cc55475b719db3a/65266c5d2cc55475b719dbea_favicon-killbillz%201.svg
    assignees:
      - bgdtc
      - shurimaTN
      - basileFernandez

  - name: KillBills Receipts Ingestion
    url: $RECEIPTS_URL
    method: POST
    expectedStatusCodes:
      - 200
    maxResponseTime: 5000
    headers:
      - "Content-Type: application/json"
      - "Authorization: hmac $RECEIPT_ENCODED_HMAC"
    body: '$RECEIPT_BODY'
    icon: https://clipart-library.com/newhp/02a163gg.jpg
    assignees:
      - bgdtc
      - shurimaTN

  - name: KillBills Transactions Ingestion
    url: $TRANSACTIONS_URL
    method: POST
    expectedStatusCodes:
      - 200
    maxResponseTime: 5000
    headers:
      - "Content-Type: application/json"
      - "Authorization: hmac $TRANSACTION_ENCODED_HMAC"
    body: '$TRANSACTION_BODY'
    icon: https://clipart-library.com/newhp/02a163gg.jpg
    assignees:
      - bgdtc
      - shurimaTN

  - name: KillBills Matching
    url: $MATCHING_URL
    method: GET
    expectedStatusCodes:
      - 200
    maxResponseTime: 5000
    icon: https://cdn-icons-png.freepik.com/512/2117/2117024.png
    assignees:
      - bgdtc
      - shurimaTN

  - name: KillBills Stores List API
    url: $STORES_URL
    method: GET
    expectedStatusCodes:
      - 200
    maxResponseTime: 10000
    headers:
      - "Content-Type: application/json"
      - "Authorization: $STORES_API_KEY"
    icon: https://cdn-icons-png.flaticon.com/512/2697/2697432.png
    assignees:
      - bgdtc
      - shurimaTN
  
  - name: KillBills Receipt Retrieval API
    url: $RECEIPT_RETRIEVAL_API
    method: GET
    expectedStatusCodes:
      - 200
    maxResponseTime: 15000
    icon: https://static.vecteezy.com/system/resources/thumbnails/008/650/271/small/bill-statement-linear-icon-of-receipt-vector.jpg
    assignees:
      - bgdtc
      - shurimaTN
    


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: status.killbills.co
  baseUrl: /StatusPage
  logoUrl: https://cdn.prod.website-files.com/65266c5d2cc55475b719db3a/65266c5d2cc55475b719dbcf_killbills-green.png
  name: StatusPage
  introTitle: "**KillBills**"
  introMessage: Live Monitoring
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
